apiVersion: v1
items:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    labels:
      app: plt-redis-sentinel-reset
      version: r1.0
    name: plt-redis-sentinel-reset
  spec:
    concurrencyPolicy: Forbid
    failedJobsHistoryLimit: 3
    jobTemplate:
      metadata:
        creationTimestamp: 2019-04-13T05:37:06Z
      spec:
        template:
          metadata:
            creationTimestamp: null
          spec:
            containers:
            - args:
              - -c
              - /soju/application/script/redis-sentinel-reset.sh
              command:
              - /bin/sh
              env:
              - name: ENVIRONMENT_CONFIG_PATH
                value: /soju/config/environment/sentinelresetenvconfig-01
              image: us.gcr.io/soju-mobile-hle/redis-sentinel-reset:master1
              imagePullPolicy: IfNotPresent
              name: redis-sentinel-reset-cronjob
              ports:
              - containerPort: 26379
                protocol: TCP
              resources:
                limits:
                  cpu: 100m
                  memory: 100Mi
                requests:
                  cpu: 100m
                  memory: 100Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
              - mountPath: /soju/config/environment/
                name: envconfig-volume
              - mountPath: /soju/application/script/
                name: appscript-volume
            dnsPolicy: ClusterFirst
            restartPolicy: OnFailure
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
            volumes:
            - configMap:
                defaultMode: 420
                name: sentinelresetenvconfig-01
              name: envconfig-volume
            - configMap:
                defaultMode: 484
                name: sentinelresetscript-01
              name: appscript-volume
    schedule: '*/15 * * * *'
    startingDeadlineSeconds: 100
    successfulJobsHistoryLimit: 3
    suspend: false
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""